### ISSUE TITLE
Scores are calculated incorrectly !!

### ISSUE THREAD

**Issue by goedertw** [WebPA/WebPA#71] opened 2020-06-04 15:49 UTC
While using WebPA for a group of 250 students, I found a problem with the calculation of the scores.
It occurs in the case not all students fill in the assessment.
Below is a simplified situation from what I found in real life.

![afbeelding](https://user-images.githubusercontent.com/33165762/83768517-2cbf1880-a67f-11ea-8d1b-0b39e5015ca2.png)

I'm using WebPA with the self-evaluation disabled.
Student a, b and d did complete the assessment. Student c didn't.
Column L shows the result generated by WebPA.
Column M shows the result after applying a "fudge factor" (in this case: * 4 / 3).
This fudge factor is only applied on the scores of the first group of students!
The scores of all subsequent groups are calculated *without* the fudge factor.

I think the only correct scores would be the ones in column P.
These are based on column O.
Column O is calculated by taken the AVERAGE score of all NON-ZERO scores that one student got.
(Alternatively, you formulate this as the SUM of all scores divided by the NUMBER of NON-ZERO scores for one student.)
(Also, compare this with column L, where we take the SUM of all scores for one student,
without any compensation for the possibly different amount of scores that student got.)
To calculate column P from column O: divide by the sum of all scores in column O (in our case 1.33)
and multiply by te number of students (in this case 4).
Remark that this is very similar to (but slightly different from) the "fudge factor".

Let me know if I can do anything to help you reproduce or provide additional information.

Attached is an Excel-file that I used to find a solution, and to check several scenarios.
[bug-peer-ass.xlsx](https://github.com/WebPA/WebPA/files/4731182/bug-peer-ass.xlsx)

**Comment by Sephster** [comment] 2020-06-05 12:20
Hi @goedertw - thanks for reporting this. Could you confirm which version of WebPA you are running?  I will check this on the latest version but wanted to confirm if this is the version you are running or not.

Many thanks, Andrew

**Comment by Sephster** [comment] 2020-06-05 23:09
Hi @goedertw. I have tried to replicate this issue but I've not been able to.

If I am understanding correctly, the issue you've listed above is that students A, B, and D are being unfairly penalised because C did not provide them with a score. They are receiving a WebPA score of 0.67 instead of 1.

I've tried to replicate this bug in the latest version of WebPA and I am not able to. Please see the screenshot below:

![ezgif-3-ad703a67ac40](https://user-images.githubusercontent.com/1457058/83928958-798f1600-a789-11ea-8b14-6a47a8817a45.png)

In it, I have an assessment with 3 groups. WebPA is weighted at 50% with no late submission pentalty. For ease, I used a likert scale scoring system and everyone who completed the assessment gave their peers 5/5. 

In the first and second groups, I had one user not submit any reviews - these can be easily identified by the "no penalty" tag in the _non-submission penalty field_ column. In both groups, the students who had submitted were not penalised because one of the other members of the group did not submit any response.

If you could confirm that my understanding is correct or not that would be appreciated. Apologies if I have made a mistake with my understanding.

If you could also let me know which version of WebPA you are running and which report you ran to view the WebPA scores that would be great thanks.

Cheers for your help,
Andrew

**Comment by goedertw** [comment] 2020-06-06 09:03
I think your understanding is correct.
I used a csv-export with the grades and feedback (webpa_student_grades_comments.csv)

I asked our IT-department for the version of webPA. Hopefully they answer that question quickly.
(I'm a lecturer/tutor *using* the module, without access to the code. I reported the issue to our IT, but they answered "sorry, this is third party software, we can't do anything". So, I reported the bug to webPA directly...)

I took a quick look at the PHP code on GitHub, before I posted the issue, but I couldn't find the code calculating the scores.
Can you please point me to the PHP file and function(s) involved?

Thanks!

Op 6 jun. 2020 01:10 schreef Andrew Millington <notifications@github.com>:

Hi @goedertw<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgoedertw&data=02%7C01%7Cwim.goedertier%40hogent.be%7Cbb74c3a7b3d34ae9a13408d809a5932b%7C5cf7310e091a4bc5acd726c721d4cccd%7C1%7C0%7C637269954024068649&sdata=PGLLcBNhrRYEHA5ytj%2BxkGczTi%2B6AY6zmpDO%2BdVnNcM%3D&reserved=0>. I have tried to replicate this issue but I've not been able to.

If I am understanding correctly, the issue you've listed above is that students A, B, and D are being unfairly penalised because C did not provide them with a score. They are receiving a WebPA score of 0.67 instead of 1.

I've tried to replicate this bug in the latest version of WebPA and I am not able to. Please see the screenshot below:

[ezgif-3-ad703a67ac40]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1457058%2F83928958-798f1600-a789-11ea-8b14-6a47a8817a45.png&data=02%7C01%7Cwim.goedertier%40hogent.be%7Cbb74c3a7b3d34ae9a13408d809a5932b%7C5cf7310e091a4bc5acd726c721d4cccd%7C1%7C0%7C637269954024078607&sdata=yQiGozhbcfIH53LsGHis%2B89%2BW9fCXBWjk8PmGKD4rVQ%3D&reserved=0>

In it, I have an assessment with 3 groups. WebPA is weighted at 50% with no late submission pentalty. For ease, I used a likert scale scoring system and everyone who completed the assessment gave their peers 5/5.

In the first and second groups, I had one user not submit any reviews - these can be easily identified by the "no penalty" tag in the non-submission penalty field column. In both groups, the students who had submitted were not penalised because one of the other members of the group did not submit any response.

If you could confirm that my understanding is correct or not that would be appreciated. Apologies if I have made a mistake with my understanding.

If you could also let me know which version of WebPA you are running and which report you ran to view the WebPA scores that would be great thanks.

Cheers for your help,
Andrew

**Comment by Sephster** [comment] 2020-06-08 11:55
Thanks for the additional information @goedertw - the version of WebPA should be visible when you login to the application. It is listed in the footer area of the app. It will usually be either 2.1.10 or 3.x.

I am assuming you will be on the version 2 branch but it would good to have this confirmed as there are quite big changes under the hood between the two versions.

The scores are usually calculated using the WebPAAlgorithm class which is found in the inc/classes folder.

I will check the student_grade_comments report this evening to make sure it is working in the latest version. If you could confirm the version you are on that would be fantastic. Thanks for your help with this.

**Comment by goedertw** [comment] 2020-06-08 12:44
It seems they are using version 1.x :-(
There is a (good?) reason for that: they tuned WebPA so that we can use groups from our electronic learning environment, also they did quite some translation work.
They are planning to upgrade *some time* (!!??) in the future.

I don't think you need to check the student_grade_comments report anymore, and you can close the issue.
The short term plan is to fix the issue on our 1.x-version.
Is there a way to contact you (once the issue is closed) if I need a hint (or code review) on the 1.x-fix?

**Comment by Sephster** [comment] 2020-06-08 13:47
Ahh I see. Unfortunately I don't have access to the 1.x code as it predates the move to GitHub. I think they might struggle to upgrade the system as it I think it was written to work pre PHP 5.4 (possibly even PHP 4).

I'm currently upgrading WebPA and aim to add in translation capabilities out the box in the future but am working on modernising the codebase just now.

If you are using Moodle, Blackboard, or any LTI capable system version 2 onwards has the ability to connect to these systems without issue.

If you have twitter you can contact me `@sephster` or post a mesasge to the WebPA mailing list on Jisc. 

I will close this issue just now as I don't think there is anything we can do to resolve it. If you need assistance upgrading to a later version please do let me know and I can try my best to provide assistance with this.

All the best
Andrew

**Closed by Sephster** 2020-06-08 13:47 UTC
